name: Docker Image CI

on:
  push:
    # branches: [ "master" ]
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to docker
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Determine version
      run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag tsakidev/giteacomment:${VERSION}
        docker build . --file Dockerfile --tag tsakidev/giteacomment:latest
    - name: Docker push
      run: docker push tsakidev/giteacomment
